### ISSUE TITLE
公共变量如何定义在一个单独的文件中[vue]

### ISSUE THREAD

**Issue by humbass** [lim-f/vue-lim#1]
vue 中使用，如何写一个独立的 js 文件，里头定义一个公共变量，其他地方同步

另： 网站上可以提下 computed, watch 跟官方的一致

第一个提问题，沙发中的沙发

**Comment by theajack** [comment]
首先对你的支持表示感谢 @humbass 
网站上可以提下 computed, watch 跟官方的一致

----

这个提过了
![image](https://github.com/user-attachments/assets/24f4ad45-7466-4453-ad91-776db0f648c2)

另外独立js文件中定义公共变量还是得接入compositionAPI或者pinia，与 lim 使用不冲突。

考虑过对独立js也按照lim编译，但是这样经过import之后就不好追踪ref标记了，因为这种实在是太灵活了。

比如

```js
export function useCounter(){
    let count = 0;
    return {
        increase() {count ++},
        data: { // 这里的count可以被用在任何地方，在编译阶段在vue文件中import之后很难知道哪个是需要加 .value 的
            count, 
            a: count,
            count: 1,
        }
    }
}
```

其实这个问题 svelte 也遇到了并且没法解决，所以才有了 svelte 5 的 runes，并且强吹这个设计多么多么好，其实就是编译阶段追踪不到变量变更做的妥协罢了

**Comment by humbass** [comment]
测试过，确实可以直接定义。刚开始的时候没回过神来，多谢指导，后续的项目打算用一用
